<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../services/email/email-service.php';
// This file replaces C:\xampp\htdocs\LOVEMI\api\support\create-ticket.php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store,no-cache,must-revalidate,max-age=0');header('Pragma:no-cache');header('Expires:0');header('X-Content-Type-Options:nosniff');
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
const SUPPORT_EMAIL='eduassistasc@gmail.com';const SUPPORT_NAME='LOVEMI Support';
function out(bool $ok,string $msg,array $data=[],int $status=200):never{http_response_code($status);echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function input():array{$raw=file_get_contents('php://input');$j=json_decode((string)$raw,true);return is_array($j)?$j:$_POST;}
function cleanv(mixed $v,int $m):string{$s=trim((string)$v);return function_exists('mb_substr')?mb_substr($s,0,$m,'UTF-8'):substr($s,0,$m);}
function esc(string $s):string{return htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function appUrl():string{$c=getenv('LOVEMI_APP_URL');if(is_string($c)&&trim($c)!=='')return rtrim(trim($c),'/');$https=(!empty($_SERVER['HTTPS'])&&strtolower((string)$_SERVER['HTTPS'])!=='off')||(int)($_SERVER['SERVER_PORT']??80)===443;$h=trim((string)($_SERVER['HTTP_HOST']??$_SERVER['SERVER_NAME']??'localhost'))?:'localhost';return ($https?'https':'http').'://'.$h.'/LOVEMI';}
function mailer(string $to,string $name,string $subject,string $html,string $text=''):bool{try{return sendLovemiEmail($to,$name,$subject,$html,$text?:strip_tags($html));}catch(Throwable $e){error_log('[LOVEMI SUPPORT MAIL] '.$e->getMessage());return false;}}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')out(false,'Only POST requests are allowed.',['code'=>'METHOD_NOT_ALLOWED'],405);
$in=input();$name=cleanv($in['name']??'',120);$email=cleanv($in['email']??'',190);$category=strtolower(cleanv($in['category']??'other',40));$subject=cleanv($in['subject']??'',180);$message=cleanv($in['message']??'',5000);$source=strtolower(cleanv($in['source']??'',20));
if($source===''){$ref=(string)($_SERVER['HTTP_REFERER']??'');$source=(stripos($ref,'contact.html')!==false)?'contact':'help';}if(!in_array($source,['help','contact'],true))$source='help';
if($name==='')out(false,'Your name is required.',['code'=>'NAME_REQUIRED'],422);if(!filter_var($email,FILTER_VALIDATE_EMAIL)||preg_match('/[\r\n]/',$email))out(false,'Please provide a valid email address.',['code'=>'INVALID_EMAIL'],422);if($subject==='')out(false,'Subject is required.',['code'=>'SUBJECT_REQUIRED'],422);if(preg_match('/[\r\n]/',$subject))out(false,'Invalid subject.',['code'=>'INVALID_SUBJECT'],422);if($message==='')out(false,'Please enter your message.',['code'=>'MESSAGE_REQUIRED'],422);
try{$pdo=db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);}catch(Throwable $e){out(false,'Database connection failed.',['code'=>'DATABASE_ERROR'],500);}
function col(PDO $pdo,string $t,string $c):bool{$s=$pdo->prepare('SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c');$s->execute([':t'=>$t,':c'=>$c]);return (int)$s->fetchColumn()>0;}function addc(PDO $pdo,string $t,string $c,string $d):void{if(!col($pdo,$t,$c))$pdo->exec("ALTER TABLE `$t` ADD COLUMN `$c` $d");}
$pdo->exec("CREATE TABLE IF NOT EXISTS support_tickets (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NULL,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,category VARCHAR(40) NOT NULL DEFAULT 'other',subject VARCHAR(180) NOT NULL,message TEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'open',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_support_user_id(user_id),KEY idx_support_email(email),KEY idx_support_status(status),KEY idx_support_created_at(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
foreach([['source',"VARCHAR(20) NOT NULL DEFAULT 'help'"],['last_user_reply_at','DATETIME NULL'],['last_admin_reply_at','DATETIME NULL'],['last_message_at','DATETIME NULL'],['close_at','DATETIME NULL'],['solved_at','DATETIME NULL'],['closed_at','DATETIME NULL'],['reminder_24_sent','TINYINT(1) NOT NULL DEFAULT 0'],['reminder_12_sent','TINYINT(1) NOT NULL DEFAULT 0'],['reminder_1_sent','TINYINT(1) NOT NULL DEFAULT 0'],['admin_last_reminder_at','DATETIME NULL']] as $x)addc($pdo,'support_tickets',$x[0],$x[1]);
$pdo->exec("CREATE TABLE IF NOT EXISTS support_ticket_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,ticket_id BIGINT UNSIGNED NOT NULL,sender_type VARCHAR(20) NOT NULL,sender_id BIGINT UNSIGNED NULL,sender_name VARCHAR(180) NOT NULL,sender_email VARCHAR(190) NOT NULL,body TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_stm_ticket(ticket_id),KEY idx_stm_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS support_ticket_access (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,ticket_id BIGINT UNSIGNED NOT NULL,access_type VARCHAR(20) NOT NULL DEFAULT 'guest',token_hash CHAR(64) NOT NULL,email_code_hash CHAR(64) NULL,email_code_expires_at DATETIME NULL,email_code_attempts INT UNSIGNED NOT NULL DEFAULT 0,email_code_sent_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_sta_ticket(ticket_id),UNIQUE KEY uq_sta_token(token_hash)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$userId=(int)($_SESSION['lovemi_user_id']??0);$currentUser=null;if($userId>0){$s=$pdo->prepare('SELECT id,username,full_names,email FROM users WHERE id=:id LIMIT 1');$s->execute([':id'=>$userId]);$currentUser=$s->fetch(PDO::FETCH_ASSOC)?:null;if(!$currentUser)$userId=0;}
$dup=$pdo->prepare('SELECT id FROM support_tickets WHERE email=:e AND subject=:s AND message=:m AND created_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 5 MINUTE) ORDER BY id DESC LIMIT 1');$dup->execute([':e'=>$email,':s'=>$subject,':m'=>$message]);$duplicateId=$dup->fetchColumn();
if($duplicateId){$id=(int)$duplicateId;$a=$pdo->prepare('SELECT token_hash,access_type FROM support_ticket_access WHERE ticket_id=:id LIMIT 1');$a->execute([':id'=>$id]);$row=$a->fetch(PDO::FETCH_ASSOC);out(true,'This support request was already submitted recently.',['ticket_id'=>$id,'ticket_number'=>'LM-TKT-'.str_pad((string)$id,6,'0',STR_PAD_LEFT),'duplicate'=>true,'email_sent'=>true,'source'=>$source]);}
$token=bin2hex(random_bytes(48));$pdo->beginTransaction();try{$status='awaiting_admin';$st=$pdo->prepare("INSERT INTO support_tickets(user_id,name,email,category,subject,message,status,source,last_user_reply_at,last_message_at) VALUES(:uid,:name,:email,:category,:subject,:message,:status,:source,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");$st->execute([':uid'=>$userId>0?$userId:null,':name'=>$name,':email'=>$email,':category'=>in_array($category,['account','login','premium','profile','connection','report','technical','contact','other'],true)?$category:'other',':subject'=>$subject,':message'=>$message,':status'=>$status,':source'=>$source]);$ticketId=(int)$pdo->lastInsertId();$m=$pdo->prepare("INSERT INTO support_ticket_messages(ticket_id,sender_type,sender_id,sender_name,sender_email,body) VALUES(:tid,'user',:sid,:name,:email,:body)");$m->execute([':tid'=>$ticketId,':sid'=>$userId>0?$userId:null,':name'=>$name,':email'=>$email,':body'=>$message]);$a=$pdo->prepare('INSERT INTO support_ticket_access(ticket_id,access_type,token_hash) VALUES(:tid,:type,:hash)');$a->execute([':tid'=>$ticketId,':type'=>$userId>0?'account':'guest',':hash'=>hash('sha256',$token)]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[LOVEMI SUPPORT INSERT] '.$e->getMessage());out(false,'The support ticket could not be saved.',['code'=>'TICKET_SAVE_FAILED'],500);}
$ticketNumber='LM-TKT-'.str_pad((string)$ticketId,6,'0',STR_PAD_LEFT);$feedbackUrl=appUrl().'/Support-Ticket-Feedback.html?token='.rawurlencode($token);$safeName=esc($name);$safeSubject=esc($subject);$safeMessage=nl2br(esc($message));$safeCategory=esc(ucfirst($category));
$adminHtml='<div style="font-family:Arial,sans-serif;background:#f7f7fb;padding:26px"><div style="max-width:700px;margin:auto;background:#fff;border-radius:18px;overflow:hidden"><div style="padding:24px;background:linear-gradient(135deg,#6d28d9,#db2777);color:#fff"><strong>LOVEMI SUPPORT</strong><h2 style="margin:7px 0">New support ticket</h2><div>'.$ticketNumber.'</div></div><div style="padding:28px"><p><strong>Source:</strong> '.esc($source==='contact'?'Contact Center':'Help Center').'</p><p><strong>Name:</strong> '.$safeName.'</p><p><strong>Email:</strong> '.esc($email).'</p><p><strong>Category:</strong> '.$safeCategory.'</p><p><strong>Subject:</strong> '.$safeSubject.'</p><div style="margin-top:18px;padding:18px;background:#faf9fc;border-radius:12px"><strong>Message</strong><div style="margin-top:10px;line-height:1.7">'.$safeMessage.'</div></div><p style="color:#777;font-size:12px">A secure feedback link was generated for two-way communication.</p></div></div></div>';
$adminText="LOVEMI SUPPORT TICKET\n\nTicket: {$ticketNumber}\nSource: {$source}\nName: {$name}\nEmail: {$email}\nCategory: {$category}\nSubject: {$subject}\n\n{$message}";
$mailAdmin=mailer(SUPPORT_EMAIL,SUPPORT_NAME,'[LOVEMI SUPPORT] '.$ticketNumber.' - '.$subject,$adminHtml,$adminText);
$confirmationHtml='<div style="font-family:Arial,sans-serif;background:#f7f7fb;padding:26px"><div style="max-width:650px;margin:auto;background:#fff;border-radius:18px;padding:28px"><h2 style="color:#6d28d9">LOVEMI Support</h2><p>Hello '.$safeName.',</p><p>Your support message has been received.</p><div style="padding:16px;background:#faf9fc;border-radius:12px"><strong>Ticket:</strong> '.$ticketNumber.'<br><strong>Source:</strong> '.esc($source==='contact'?'Contact Center':'Help Center').'<br><strong>Subject:</strong> '.$safeSubject.'</div><p>Use the secure link below to view the conversation and reply to support:</p><p><a href="'.esc($feedbackUrl).'" style="display:inline-block;padding:13px 20px;border-radius:11px;background:#6d28d9;color:#fff;text-decoration:none;font-weight:800">Open Support Conversation</a></p><p style="font-size:12px;color:#777">Keep this link private. Account holders will also complete LOVEMI email and 2FA checks before seeing the ticket.</p></div></div>';
$confirm=mailer($email,$name,'LOVEMI Support ticket received - '.$ticketNumber,$confirmationHtml,"Your LOVEMI support ticket {$ticketNumber} was received. Open: {$feedbackUrl}");
try{$pdo->prepare("UPDATE support_tickets SET status=IF(:mail=1,'received','awaiting_admin'),updated_at=CURRENT_TIMESTAMP WHERE id=:id LIMIT 1")->execute([':mail'=>$mailAdmin?1:0,':id'=>$ticketId]);}catch(Throwable $e){}
out(true,'Your support ticket has been submitted.',['ticket_id'=>$ticketId,'ticket_number'=>$ticketNumber,'source'=>$source,'feedback_url'=>$feedbackUrl,'email_sent'=>$mailAdmin,'confirmation_sent'=>$confirm,'status'=>$mailAdmin?'received':'awaiting_admin'],201);
