
"use strict";
const API={open:"api/support/feedback/open.php",sendCode:"api/support/feedback/send-email-code.php",verifyEmail:"api/support/feedback/verify-email.php",verify2fa:"api/support/feedback/verify-2fa.php",reply:"api/support/feedback/reply.php",status:"api/support/feedback/status.php"};
const token=new URLSearchParams(location.search).get('token')||'';const state={ticket:null,messages:[],loaded:false};const $=id=>document.getElementById(id);
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}function dt(v){if(!v)return'—';const d=new Date(String(v).replace(' ','T'));return Number.isNaN(d.getTime())?String(v):d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
async function json(url,opt={}){const sep=url.includes('?')?'&':'?';const r=await fetch(url+sep+'_='+Date.now(),{...opt,cache:'no-store',credentials:'same-origin',headers:{Accept:'application/json','Cache-Control':'no-cache,no-store,max-age=0',...(opt.headers||{})}});const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw new Error('The support server returned an invalid response.')}if(!r.ok||j.success===false)throw Object.assign(new Error(j.message||'Request failed.'),{code:j.code,status:r.status});return j}
function show(view){['loadingView','blockedView','verifyView','conversationView'].forEach(id=>$(id).hidden=id!==view)}function status(m,type='info'){const b=$('verifyStatus');if(b){b.className='status show '+(type==='ok'?'ok':'err');b.textContent=m}}
function actionStatus(m,type='ok'){const b=$('actionStatus');b.className='status show '+(type==='ok'?'ok':'err');b.textContent=m;clearTimeout(actionStatus.t);actionStatus.t=setTimeout(()=>b.className='status',3500)}
function render(){const t=state.ticket;$('ticketSubject').textContent=t.subject||'Support ticket';$('ticketMeta').textContent=`${t.name||'Visitor'} • ${t.email||''}`;$('ticketChips').innerHTML=`<span class="chip source">${esc(t.source_label)}</span><span class="chip ${String(t.status)==='closed'?'closed':String(t.status)==='awaiting_user'?'wait':String(t.status)==='awaiting_admin'?'reply':''}">${esc(t.status_label)}</span><span class="chip">LM-TKT-${String(t.id).padStart(6,'0')}</span>`;$('iTicket').textContent='LM-TKT-'+String(t.id).padStart(6,'0');$('iSource').textContent=t.source_label;$('iCategory').textContent=t.category||'—';$('iCreated').textContent=dt(t.created_at);$('sourceExplain').textContent=t.source==='contact'?'This conversation started from Contact Center.':'This conversation started from Help Center.';$('closeCount').textContent=t.close_at&&['awaiting_user','solved'].includes(String(t.status))?remainingText(t.close_at):'No timer';$('solveBtn').disabled=String(t.status)==='closed';$('closeBtn').disabled=String(t.status)==='closed';$('replyBox').disabled=String(t.status)==='closed';$('replyBtn').disabled=String(t.status)==='closed';const box=$('messages');box.innerHTML=(state.messages||[]).map(m=>`<div class="bubble-wrap ${m.sender_type==='admin'?'admin':''}"><div class="bubble"><div class="sender">${esc(m.sender_name)} · ${m.sender_type==='admin'?'LOVEMI Support':'You'}</div><div class="body">${esc(m.body)}</div><div class="when">${esc(dt(m.created_at))}</div></div></div>`).join('')||'<p class="info">No messages yet.</p>';box.scrollTop=box.scrollHeight}
function remainingText(v){const ms=new Date(String(v).replace(' ','T')).getTime()-Date.now();if(ms<=0)return'Closing soon';const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;if(h>=24){const d=Math.floor(h/24);return`${d}d ${h%24}h`}return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
async function load(){if(!token){show('blockedView');return}try{const d=await json(API.open+'?token='+encodeURIComponent(token));state.ticket=d.ticket;if(d.access_granted){state.messages=d.messages||[];show('conversationView');render();return}$('emailMask').textContent=d.email_mask||'your account email';show('verifyView');if(d.verification_required==='email'){status('Email verification is required before the conversation can be displayed.','err')}else if(d.verification_required==='2fa'){status('Your email is verified. Complete LOVEMI 2FA to continue.','err')}else{status('Complete the required verification steps to continue.','err')}}catch(e){$('blockedText').textContent=e.message||'This support link is invalid.';show('blockedView')}}
$('sendCodeBtn').addEventListener('click',async()=>{try{const d=await json(API.sendCode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});status(d.message||'Verification code sent.','ok')}catch(e){status(e.message,'err')}});$('verifyEmailBtn').addEventListener('click',async()=>{try{const d=await json(API.verifyEmail,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,code:$('emailCode').value.trim()})});status(d.message||'Email verified.','ok');await load()}catch(e){status(e.message,'err')}});$('verify2faBtn').addEventListener('click',async()=>{try{const d=await json(API.verify2fa,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});if(d.access_granted){await load();return}status(d.message,'err')}catch(e){status(e.message,'err');if(e.code==='TWO_FACTOR_REQUIRED')$('twoFaLink').style.display='inline-flex'}});
$('replyForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('replyBox').value.trim();if(!msg||!state.ticket)return;const b=$('replyBtn');b.disabled=true;try{const d=await json(API.reply,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,message:msg})});$('replyBox').value='';actionStatus(d.message||'Reply sent.');await load()}catch(err){actionStatus(err.message,'err')}finally{b.disabled=false;$('replyBtn').disabled=state.ticket?.status==='closed'}});$('solveBtn').addEventListener('click',async()=>{try{const d=await json(API.status,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'solve'})});actionStatus(d.message);await load()}catch(e){actionStatus(e.message,'err')}});$('closeBtn').addEventListener('click',async()=>{if(!confirm('Close this support conversation now?'))return;try{const d=await json(API.status,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'close'})});actionStatus(d.message);await load()}catch(e){actionStatus(e.message,'err')}});
setInterval(async()=>{if(!state.loaded&&$('conversationView').hidden)return;try{const d=await json(API.open+'?token='+encodeURIComponent(token));if(d.access_granted){state.ticket=d.ticket;state.messages=d.messages||[];state.loaded=true;render()}}catch{}},3000);setInterval(()=>{if(state.ticket)$('closeCount').textContent=state.ticket.close_at&&['awaiting_user','solved'].includes(String(state.ticket.status))?remainingText(state.ticket.close_at):'No timer'},1000);load();
