<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/database.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
function discoverResponse(bool $success,string $message,array $extra=[],int $status=200): never { http_response_code($status); echo json_encode(array_merge(['success'=>$success,'message'=>$message],$extra),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
if (($_SERVER['REQUEST_METHOD']??'') !== 'GET') discoverResponse(false,'Only GET requests are allowed.',['code'=>'METHOD_NOT_ALLOWED'],405);
$currentUserId=(int)($_SESSION['lovemi_user_id']??0);
$search=trim((string)($_GET['search']??'')); $gender=trim((string)($_GET['gender']??'')); $countryId=max(0,(int)($_GET['country_id']??0)); $limit=max(1,min(100,(int)($_GET['limit']??50))); $offset=max(0,(int)($_GET['offset']??0)); $sort=strtolower(trim((string)($_GET['sort']??'nearest')));
$lat=filter_var($_GET['lat']??null,FILTER_VALIDATE_FLOAT); $lng=filter_var($_GET['lng']??null,FILTER_VALIDATE_FLOAT);
$hasVisitorLocation=$lat!==false&&$lat!==null&&$lng!==false&&$lng!==null&&$lat>=-90&&$lat<=90&&$lng>=-180&&$lng<=180;
try{$pdo=db();}catch(Throwable $e){error_log('[LOVEMI DISCOVER USERS] '.$e->getMessage());discoverResponse(false,'Unable to connect to the database.',['users'=>[]],500);}
try{$pdo->exec("CREATE TABLE IF NOT EXISTS user_location_preferences (user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY, live_location_enabled TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$pdo->exec("CREATE TABLE IF NOT EXISTS user_live_locations (user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, accuracy_meters DECIMAL(10,2) NULL, altitude_meters DECIMAL(10,2) NULL, heading DECIMAL(10,2) NULL, speed_mps DECIMAL(10,2) NULL, country_name VARCHAR(120) NULL, region_name VARCHAR(160) NULL, city_name VARCHAR(160) NULL, location_enabled TINYINT(1) NOT NULL DEFAULT 1, last_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_live_enabled(location_enabled), INDEX idx_live_updated(last_updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}catch(Throwable $e){error_log('[LOVEMI DISCOVER LOCATION TABLE] '.$e->getMessage());}
$where=["u.account_status='approved'","u.email_verified=1","u.is_active=1","u.is_suspended=0","u.is_deleted=0","(pr.profile_visibility IS NULL OR pr.profile_visibility='public')","(r.is_admin_role=0 OR r.is_admin_role IS NULL)"];
$params=[];
if($currentUserId>0){$where[]='u.id<>:current_user_id';$params[':current_user_id']=$currentUserId;}
if($search!==''){$where[]='(u.username LIKE :search OR u.full_names LIKE :search OR pr.display_name LIKE :search OR pr.bio LIKE :search OR pr.city LIKE :search OR c.name LIKE :search)';$params[':search']='%'.$search.'%';}
if($gender!==''){$where[]='u.gender=:gender';$params[':gender']=$gender;}
if($countryId>0){$where[]='u.country_id=:country_id';$params[':country_id']=$countryId;}
$distanceExpr='NULL';
if($hasVisitorLocation){$distanceExpr='(6371 * 2 * ASIN(SQRT(POW(SIN(RADIANS(ull.latitude-'.(float)$lat.')/2),2) + COS(RADIANS('.(float)$lat.')) * COS(RADIANS(ull.latitude)) * POW(SIN(RADIANS(ull.longitude-'.(float)$lng.')/2),2))))';}
$sql="SELECT u.id,u.username,u.full_names,u.gender,u.country_id,u.date_of_birth,u.email_verified,u.identity_verified,u.age_verified,u.account_status,u.created_at,u.last_seen_at,c.name AS country_name,c.iso2 AS country_iso2,pr.display_name,pr.bio,pr.occupation,pr.education,pr.city,pr.relationship_status,pr.looking_for,pr.interests,pr.profile_visibility,pr.show_online_status,pr.allow_messages,(SELECT ph.file_path FROM photos ph WHERE ph.user_id=u.id AND ph.photo_type='profile' AND ph.approval_status='approved' AND ph.is_primary=1 ORDER BY ph.id DESC LIMIT 1) AS profile_photo,(SELECT ph.thumbnail_path FROM photos ph WHERE ph.user_id=u.id AND ph.photo_type='profile' AND ph.approval_status='approved' AND ph.is_primary=1 ORDER BY ph.id DESC LIMIT 1) AS profile_thumbnail,CASE WHEN EXISTS(SELECT 1 FROM user_sessions us WHERE us.user_id=u.id AND us.revoked_at IS NULL AND us.two_factor_passed=1 AND us.expires_at>CURRENT_TIMESTAMP AND us.last_activity_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 10 MINUTE)) THEN 1 ELSE 0 END AS is_online,ull.latitude AS live_latitude,ull.longitude AS live_longitude,ull.city_name AS current_city,ull.region_name AS current_region,ull.country_name AS current_country,ull.last_updated_at AS location_updated_at,ull.location_enabled AS live_location_enabled,{$distanceExpr} AS distance_km FROM users u LEFT JOIN roles r ON r.id=u.role_id LEFT JOIN countries c ON c.id=u.country_id LEFT JOIN profiles pr ON pr.user_id=u.id LEFT JOIN user_live_locations ull ON ull.user_id=u.id AND ull.location_enabled=1 AND EXISTS(SELECT 1 FROM user_location_preferences ulp WHERE ulp.user_id=u.id AND ulp.live_location_enabled=1) WHERE ".implode(' AND ',$where);
$order='u.created_at DESC,u.id DESC';
if($sort==='name')$order='COALESCE(pr.display_name,u.full_names,u.username) ASC,u.id DESC';elseif($sort==='online')$order='is_online DESC,u.last_seen_at DESC,u.id DESC';elseif($sort==='nearest'&&$hasVisitorLocation)$order='CASE WHEN distance_km IS NULL THEN 1 ELSE 0 END ASC,distance_km ASC,u.created_at DESC,u.id DESC';
$sql.=" ORDER BY {$order} LIMIT :limit OFFSET :offset";
try{$stmt=$pdo->prepare($sql);foreach($params as $k=>$v)$stmt->bindValue($k,$v);$stmt->bindValue(':limit',$limit,PDO::PARAM_INT);$stmt->bindValue(':offset',$offset,PDO::PARAM_INT);$stmt->execute();$rows=$stmt->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){error_log('[LOVEMI DISCOVER USERS QUERY] '.$e->getMessage());discoverResponse(false,'Unable to load LOVEMI members.',['users'=>[]],500);}
$users=[];foreach($rows as $row){$distance=$row['distance_km']!==null?(float)$row['distance_km']:null;$liveEnabled=(int)($row['live_location_enabled']??0)===1;$currentCity=trim((string)($row['current_city']??''));$currentRegion=trim((string)($row['current_region']??''));$currentCountry=trim((string)($row['current_country']??''));$label='';if($liveEnabled){if($currentCity!=='')$label=$currentCity;elseif($currentRegion!=='')$label=$currentRegion;elseif($currentCountry!=='')$label=$currentCountry;} $users[]=['id'=>(int)$row['id'],'user_id'=>(int)$row['id'],'username'=>(string)$row['username'],'full_names'=>(string)$row['full_names'],'full_name'=>(string)$row['full_names'],'gender'=>(string)$row['gender'],'country_id'=>(int)$row['country_id'],'country_name'=>$row['country_name']!==null?(string)$row['country_name']:null,'country_iso2'=>$row['country_iso2']!==null?(string)$row['country_iso2']:null,'display_name'=>$row['display_name']!==null?(string)$row['display_name']:null,'bio'=>$row['bio']!==null?(string)$row['bio']:null,'city'=>$row['city']!==null?(string)$row['city']:null,'profile_photo'=>$row['profile_photo']!==null?(string)$row['profile_photo']:null,'profile_thumbnail'=>$row['profile_thumbnail']!==null?(string)$row['profile_thumbnail']:null,'photo_url'=>$row['profile_photo']!==null?(string)$row['profile_photo']:null,'is_online'=>(bool)$row['is_online'],'online'=>(bool)$row['is_online'],'last_seen_at'=>$row['last_seen_at']!==null?(string)$row['last_seen_at']:null,'created_at'=>(string)$row['created_at'],'distance_km'=>$distance,'current_location_label'=>$label,'current_city'=>$liveEnabled?$currentCity:null,'current_region'=>$liveEnabled?$currentRegion:null,'current_country'=>$liveEnabled?$currentCountry:null,'location_updated_at'=>$liveEnabled&&$row['location_updated_at']!==null?(string)$row['location_updated_at']:null,'location_hidden'=>!$liveEnabled];}
discoverResponse(true,'Approved LOVEMI members loaded successfully.',['count'=>count($users),'users'=>$users,'data'=>$users,'visitor_location'=>$hasVisitorLocation?['latitude'=>(float)$lat,'longitude'=>(float)$lng]:null]);
