<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/database.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');header('Expires: 0');header('X-Content-Type-Options: nosniff');header('Content-Disposition: inline');
$photoId=(int)($_GET['photo_id']??0);if($photoId<=0){http_response_code(404);exit;}
try{$pdo=db();$stmt=$pdo->prepare("SELECT ph.file_path,ph.mime_type,ph.file_name,p.id AS post_id,p.approval_status,p.visibility,p.deleted_at,u.is_active,u.is_suspended,u.is_deleted,u.email_verified,u.account_status,r.is_admin_role FROM photos ph INNER JOIN post_photos pp ON pp.photo_id=ph.id INNER JOIN posts p ON p.id=pp.post_id INNER JOIN users u ON u.id=p.user_id LEFT JOIN roles r ON r.id=u.role_id WHERE ph.id=:photo_id AND ph.approval_status='approved' AND p.approval_status='approved' AND p.visibility='public' AND p.deleted_at IS NULL AND u.email_verified=1 AND u.is_active=1 AND u.is_suspended=0 AND u.is_deleted=0 AND (r.is_admin_role=0 OR r.is_admin_role IS NULL) LIMIT 1");$stmt->execute([':photo_id'=>$photoId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row){http_response_code(404);exit;}$relative=ltrim(str_replace('\\','/',(string)$row['file_path']),'/');if(str_contains($relative,'..')){http_response_code(404);exit;}$root=realpath(__DIR__.'/../..');$file=realpath($root.DIRECTORY_SEPARATOR.$relative);if(!$file||!is_file($file)||!str_starts_with($file,$root.DIRECTORY_SEPARATOR)){http_response_code(404);exit;}$mime=(string)($row['mime_type']??'application/octet-stream');$allowed=['image/jpeg','image/png','image/gif','image/webp','image/bmp','video/mp4','video/webm','video/ogg','video/quicktime'];if(!in_array(strtolower($mime),$allowed,true))$mime='application/octet-stream';
$size=filesize($file);header('Content-Type: '.$mime);header('Accept-Ranges: bytes');
$start=0;$end=max(0,$size-1);$length=$size;$range=$_SERVER['HTTP_RANGE']??'';
if($range&&preg_match('/bytes=(\d*)-(\d*)/',$range,$m)){if($m[1]===''&&$m[2]!==''){$suffix=(int)$m[2];$start=max(0,$size-$suffix);}else{$start=(int)$m[1];if($m[2]!=='')$end=(int)$m[2];}if($end>$size-1)$end=$size-1;if($start>$end||$start<0){header("Content-Range: bytes */{$size}");http_response_code(416);exit;}http_response_code(206);$length=$end-$start+1;header("Content-Range: bytes {$start}-{$end}/{$size}");}
header('Content-Length: '.(string)$length);$fh=fopen($file,'rb');if(!$fh){http_response_code(500);exit;}fseek($fh,$start);$chunk=1024*1024;$remaining=$length;while($remaining>0&&!feof($fh)){$read=fread($fh,min($chunk,$remaining));if($read===false)break;echo $read;$remaining-=strlen($read);if(function_exists('fastcgi_finish_request')){} flush();}fclose($fh);exit;
}catch(Throwable $e){error_log('[LOVEMI DISCOVER MEDIA] '.$e->getMessage());http_response_code(500);exit;}
