<?php
declare(strict_types=1);
require_once __DIR__ . '/../../../config/database.php';
require_once __DIR__ . '/../../../services/email/email-service.php';
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
const FB_SUPPORT_EMAIL='eduassistasc@gmail.com'; const FB_SUPPORT_NAME='LOVEMI Support';
function fb_out(bool $ok,string $msg,array $data=[],int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store,no-cache,must-revalidate,max-age=0');header('Pragma:no-cache');header('Expires:0');header('X-Content-Type-Options:nosniff');echo json_encode(array_merge(['success'=>$ok,'message'=>$msg],$data),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function fb_in():array{$raw=file_get_contents('php://input');$j=json_decode((string)$raw,true);return is_array($j)?$j:$_POST;}
function fb_clean(mixed $v,int $m):string{$s=trim((string)$v);return function_exists('mb_substr')?mb_substr($s,0,$m,'UTF-8'):substr($s,0,$m);}
function fb_esc(string $s):string{return htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function fb_app():string{$c=getenv('LOVEMI_APP_URL');if(is_string($c)&&trim($c)!=='')return rtrim(trim($c),'/');$https=(!empty($_SERVER['HTTPS'])&&strtolower((string)$_SERVER['HTTPS'])!=='off')||(int)($_SERVER['SERVER_PORT']??80)===443;$h=trim((string)($_SERVER['HTTP_HOST']??$_SERVER['SERVER_NAME']??'localhost'))?:'localhost';return ($https?'https':'http').'://'.$h.'/LOVEMI';}
function fb_url(string $token):string{return fb_app().'/Support-Ticket-Feedback.html?token='.rawurlencode($token);}
function fb_mail(string $to,string $name,string $subject,string $html,string $text=''):bool{try{return sendLovemiEmail($to,$name,$subject,$html,$text?:strip_tags($html));}catch(Throwable $e){error_log('[LOVEMI SUPPORT FEEDBACK MAIL] '.$e->getMessage());return false;}}
function fb_pdo():PDO{$pdo=db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);return $pdo;}
function fb_col(PDO $pdo,string $table,string $col):bool{$s=$pdo->prepare('SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c');$s->execute([':t'=>$table,':c'=>$col]);return (int)$s->fetchColumn()>0;}
function fb_addc(PDO $pdo,string $table,string $col,string $def):void{if(!fb_col($pdo,$table,$col))$pdo->exec("ALTER TABLE `$table` ADD COLUMN `$col` $def");}
function fb_schema(PDO $pdo):void{$pdo->exec("CREATE TABLE IF NOT EXISTS support_ticket_messages(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,ticket_id BIGINT UNSIGNED NOT NULL,sender_type VARCHAR(20) NOT NULL,sender_id BIGINT UNSIGNED NULL,sender_name VARCHAR(180) NOT NULL,sender_email VARCHAR(190) NOT NULL,body TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_stm_ticket(ticket_id),KEY idx_stm_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$pdo->exec("CREATE TABLE IF NOT EXISTS support_ticket_access(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,ticket_id BIGINT UNSIGNED NOT NULL,access_type VARCHAR(20) NOT NULL DEFAULT 'guest',token_hash CHAR(64) NOT NULL,email_code_hash CHAR(64) NULL,email_code_expires_at DATETIME NULL,email_code_attempts INT UNSIGNED NOT NULL DEFAULT 0,email_code_sent_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_sta_ticket(ticket_id),UNIQUE KEY uq_sta_token(token_hash)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");foreach([['source',"VARCHAR(20) NOT NULL DEFAULT 'help'"],['last_user_reply_at','DATETIME NULL'],['last_admin_reply_at','DATETIME NULL'],['last_message_at','DATETIME NULL'],['close_at','DATETIME NULL'],['solved_at','DATETIME NULL'],['closed_at','DATETIME NULL'],['reminder_24_sent','TINYINT(1) NOT NULL DEFAULT 0'],['reminder_12_sent','TINYINT(1) NOT NULL DEFAULT 0'],['reminder_1_sent','TINYINT(1) NOT NULL DEFAULT 0'],['admin_last_reminder_at','DATETIME NULL']] as $x)fb_addc($pdo,'support_tickets',$x[0],$x[1]);}
function fb_access(PDO $pdo,string $token):?array{$token=trim($token);if($token==='')return null;$s=$pdo->prepare('SELECT a.id AS access_id,a.ticket_id,a.access_type,a.email_code_hash,a.email_code_expires_at,a.email_code_attempts,a.email_code_sent_at,t.user_id,t.name,t.email,t.category,t.subject,t.message,t.status,t.source,t.created_at,t.updated_at,t.last_user_reply_at,t.last_admin_reply_at,t.last_message_at,t.close_at,t.solved_at,t.closed_at FROM support_ticket_access a JOIN support_tickets t ON t.id=a.ticket_id WHERE a.token_hash=:h LIMIT 1');$s->execute([':h'=>hash('sha256',$token)]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null;}
function fb_session_user(PDO $pdo):?array{$uid=(int)($_SESSION['lovemi_user_id']??0);$tok=trim((string)($_SESSION['lovemi_session_token']??''));if($uid<=0||$tok==='')return null;$s=$pdo->prepare('SELECT us.id,us.user_id,us.two_factor_passed,us.expires_at,us.revoked_at,u.email,u.full_names,u.username FROM user_sessions us JOIN users u ON u.id=us.user_id WHERE us.user_id=:uid AND us.session_token_hash=:h LIMIT 1');$s->execute([':uid'=>$uid,':h'=>hash('sha256',$tok)]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r||!empty($r['revoked_at'])||(isset($r['expires_at'])&&strtotime((string)$r['expires_at'])<time()))return null;return $r;}
function fb_email_ok(int $accessId):bool{$a=$_SESSION['lovemi_support_email_verified'][$accessId]??0;return is_numeric($a)&&(int)$a>time();}
function fb_2fa_ok(int $accessId):bool{$a=$_SESSION['lovemi_support_2fa_verified'][$accessId]??0;return is_numeric($a)&&(int)$a>time();}
function fb_authorized(PDO $pdo,array $ticket):array{$accessType=(string)($ticket['access_type']??'guest');if(in_array($accessType,['guest','direct'],true))return ['ok'=>true,'reason'=>$accessType,'user'=>null];$u=fb_session_user($pdo);if(!$u||((int)$u['user_id']!==(int)($ticket['user_id']??0)))return ['ok'=>false,'reason'=>'login','user'=>$u];$accessId=(int)$ticket['access_id'];if(!fb_email_ok($accessId))return ['ok'=>false,'reason'=>'email','user'=>$u];if(!fb_2fa_ok($accessId))return ['ok'=>false,'reason'=>'2fa','user'=>$u];return ['ok'=>true,'reason'=>'granted','user'=>$u];}
function fb_messages(PDO $pdo,int $ticketId):array{$s=$pdo->prepare('SELECT id,ticket_id,sender_type,sender_id,sender_name,sender_email,body,created_at FROM support_ticket_messages WHERE ticket_id=:id ORDER BY id ASC');$s->execute([':id'=>$ticketId]);return $s->fetchAll(PDO::FETCH_ASSOC);}
function fb_notify_user(PDO $pdo,int $uid,string $title,string $message,int $ticketId):void{if($uid<=0)return;try{$s=$pdo->prepare("INSERT INTO notifications(user_id,notification_type_id,sender_id,title,message,reference_type,reference_id,is_read) VALUES(:u,NULL,NULL,:t,:m,'support_ticket',:r,0)");$s->execute([':u'=>$uid,':t'=>$title,':m'=>$message,':r'=>$ticketId]);}catch(Throwable $e){error_log('[LOVEMI SUPPORT FEEDBACK NOTIFY USER] '.$e->getMessage());}}
function fb_notify_admins(PDO $pdo,string $title,string $message,int $ticketId):void{try{$q=$pdo->query("SELECT u.id FROM users u JOIN roles r ON r.id=u.role_id WHERE r.is_admin_role=1 AND u.is_active=1 AND u.is_suspended=0 AND u.is_deleted=0");$ids=$q?$q->fetchAll(PDO::FETCH_COLUMN):[];}catch(Throwable){$ids=[];}$s=$pdo->prepare("INSERT INTO notifications(user_id,notification_type_id,sender_id,title,message,reference_type,reference_id,is_read) VALUES(:u,NULL,NULL,:t,:m,'support_ticket',:r,0)");foreach($ids as $id){try{$s->execute([':u'=>(int)$id,':t'=>$title,':m'=>$message,':r'=>$ticketId]);}catch(Throwable $e){}}}
function fb_rotate_token(PDO $pdo,int $ticketId):string{$token=bin2hex(random_bytes(48));$s=$pdo->prepare('UPDATE support_ticket_access SET token_hash=:h,updated_at=CURRENT_TIMESTAMP WHERE ticket_id=:id LIMIT 1');$s->execute([':h'=>hash('sha256',$token),':id'=>$ticketId]);return $token;}
function fb_user_mail(PDO $pdo,array $ticket,string $body,string $feedbackUrl,string $direction='admin'):bool{$label=$direction==='admin'?'LOVEMI Support replied':'The user replied to LOVEMI Support';$html='<div style="font-family:Arial,sans-serif;background:#f7f7fb;padding:26px"><div style="max-width:680px;margin:auto;background:#fff;border-radius:18px;padding:28px"><h2 style="color:#6d28d9">'.$label.'</h2><p>Hello '.fb_esc((string)$ticket['name']).',</p><p>Ticket <strong>LM-TKT-'.str_pad((string)$ticket['id'],6,'0',STR_PAD_LEFT).'</strong> — '.fb_esc((string)$ticket['subject']).'</p><div style="padding:16px;background:#faf9fc;border-radius:12px;white-space:normal"><strong>Message</strong><div style="margin-top:10px;line-height:1.7">'.nl2br(fb_esc($body)).'</div></div><p><a href="'.fb_esc($feedbackUrl).'" style="display:inline-block;padding:13px 20px;border-radius:11px;background:#6d28d9;color:#fff;text-decoration:none;font-weight:800">Open Support Conversation</a></p></div></div>';return fb_mail((string)$ticket['email'],(string)$ticket['name'],$label.' - LM-TKT-'.str_pad((string)$ticket['id'],6,'0',STR_PAD_LEFT),$html);}
